-- EC site database schema for Oracle Database 12c or later.
-- Run this script while connected to the Oracle schema that will own the tables.

CREATE TABLE users (
    user_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name        VARCHAR2(100 CHAR) NOT NULL,
    email       VARCHAR2(255 CHAR) NOT NULL,
    password    VARCHAR2(255 CHAR) NOT NULL,
    phone       VARCHAR2(30 CHAR),
    address     VARCHAR2(500 CHAR),
    role        VARCHAR2(20 CHAR) DEFAULT 'CUSTOMER' NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

CREATE TABLE categories (
    category_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    category_name  VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (category_id),
    CONSTRAINT uq_categories_name UNIQUE (category_name)
);

CREATE TABLE products (
    product_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    category_id   NUMBER NOT NULL,
    product_name  VARCHAR2(200 CHAR) NOT NULL,
    description   VARCHAR2(2000 CHAR),
    price         NUMBER(12, 2) NOT NULL,
    stock         NUMBER(10) DEFAULT 0 NOT NULL,
    image_path    VARCHAR2(500 CHAR),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id)
        REFERENCES categories (category_id),
    CONSTRAINT ck_products_price CHECK (price >= 0),
    CONSTRAINT ck_products_stock CHECK (stock >= 0 AND stock = TRUNC(stock))
);

CREATE TABLE orders (
    order_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id           NUMBER NOT NULL,
    total_price       NUMBER(12, 2) NOT NULL,
    status            VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    shipping_address  VARCHAR2(500 CHAR) NOT NULL,
    order_date        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_orders_total CHECK (total_price >= 0),
    CONSTRAINT ck_orders_status CHECK (
        status IN ('PENDING', 'CONFIRMED', 'SHIPPED', 'COMPLETED', 'CANCELLED')
    )
);

CREATE TABLE order_items (
    order_item_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    order_id       NUMBER NOT NULL,
    product_id     NUMBER NOT NULL,
    quantity       NUMBER(10) NOT NULL,
    price          NUMBER(12, 2) NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (order_item_id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id)
        REFERENCES products (product_id),
    CONSTRAINT uq_order_items_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_items_quantity CHECK (
        quantity > 0 AND quantity = TRUNC(quantity)
    ),
    CONSTRAINT ck_order_items_price CHECK (price >= 0)
);

-- Sample users.
-- These passwords are demonstration placeholders only. Replace them with secure
-- password hashes before implementing login or using the application for real.
INSERT INTO users (name, email, password, phone, address, role)
VALUES ('EC Administrator', 'admin@example.com', 'CHANGE_ME_ADMIN',
        '090-0000-0001', 'Tokyo, Japan', 'ADMIN');

INSERT INTO users (name, email, password, phone, address, role)
VALUES ('Taro Yamada', 'taro@example.com', 'CHANGE_ME_TARO',
        '090-0000-0002', 'Shinjuku, Tokyo, Japan', 'CUSTOMER');

INSERT INTO users (name, email, password, phone, address, role)
VALUES ('Hanako Sato', 'hanako@example.com', 'CHANGE_ME_HANAKO',
        '090-0000-0003', 'Yokohama, Kanagawa, Japan', 'CUSTOMER');

-- Sample categories.
INSERT INTO categories (category_name) VALUES ('Electronics');
INSERT INTO categories (category_name) VALUES ('Clothing');
INSERT INTO categories (category_name) VALUES ('Home and Kitchen');
INSERT INTO categories (category_name) VALUES ('Books');

-- Sample products. Category subqueries avoid depending on generated ID values.
INSERT INTO products
    (category_id, product_name, description, price, stock, image_path)
VALUES
    ((SELECT category_id FROM categories WHERE category_name = 'Electronics'),
     'Wireless Mouse', 'Compact wireless mouse for everyday use.',
     2480, 40, 'images/products/wireless-mouse.jpg');

INSERT INTO products
    (category_id, product_name, description, price, stock, image_path)
VALUES
    ((SELECT category_id FROM categories WHERE category_name = 'Electronics'),
     'USB-C Charger', 'Fast 45-watt USB-C wall charger.',
     3980, 25, 'images/products/usb-c-charger.jpg');

INSERT INTO products
    (category_id, product_name, description, price, stock, image_path)
VALUES
    ((SELECT category_id FROM categories WHERE category_name = 'Electronics'),
     'Bluetooth Headphones', 'Over-ear wireless headphones.',
     7980, 18, 'images/products/bluetooth-headphones.jpg');

INSERT INTO products
    (category_id, product_name, description, price, stock, image_path)
VALUES
    ((SELECT category_id FROM categories WHERE category_name = 'Clothing'),
     'Cotton T-Shirt', 'Comfortable unisex cotton T-shirt.',
     1980, 60, 'images/products/cotton-t-shirt.jpg');

INSERT INTO products
    (category_id, product_name, description, price, stock, image_path)
VALUES
    ((SELECT category_id FROM categories WHERE category_name = 'Clothing'),
     'Lightweight Jacket', 'Light jacket suitable for spring and autumn.',
     6980, 20, 'images/products/lightweight-jacket.jpg');

INSERT INTO products
    (category_id, product_name, description, price, stock, image_path)
VALUES
    ((SELECT category_id FROM categories WHERE category_name = 'Home and Kitchen'),
     'Stainless Steel Bottle', 'Reusable insulated 500 ml bottle.',
     2980, 35, 'images/products/steel-bottle.jpg');

INSERT INTO products
    (category_id, product_name, description, price, stock, image_path)
VALUES
    ((SELECT category_id FROM categories WHERE category_name = 'Home and Kitchen'),
     'Ceramic Mug', 'Simple 350 ml ceramic coffee mug.',
     1280, 45, 'images/products/ceramic-mug.jpg');

INSERT INTO products
    (category_id, product_name, description, price, stock, image_path)
VALUES
    ((SELECT category_id FROM categories WHERE category_name = 'Home and Kitchen'),
     'Kitchen Scale', 'Digital kitchen scale with a clear display.',
     3480, 22, 'images/products/kitchen-scale.jpg');

INSERT INTO products
    (category_id, product_name, description, price, stock, image_path)
VALUES
    ((SELECT category_id FROM categories WHERE category_name = 'Books'),
     'Java for Beginners', 'An introductory guide to the Java language.',
     3200, 30, 'images/products/java-for-beginners.jpg');

INSERT INTO products
    (category_id, product_name, description, price, stock, image_path)
VALUES
    ((SELECT category_id FROM categories WHERE category_name = 'Books'),
     'SQL Fundamentals', 'A practical introduction to relational databases and SQL.',
     2800, 28, 'images/products/sql-fundamentals.jpg');

COMMIT;

-- ============================================================================
-- EC SITE BANNERS
-- Customer Products-page cover banners. Independent from legacy tables.
-- Run only when EC_SITE_BANNERS does not already exist.
-- ============================================================================

CREATE TABLE ec_site_banners (
    banner_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title          VARCHAR2(120 CHAR),
    image_url      VARCHAR2(500 CHAR) NOT NULL,
    link_url       VARCHAR2(500 CHAR),
    display_order  NUMBER(1) NOT NULL,
    is_active      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP,
    CONSTRAINT pk_ec_site_banners PRIMARY KEY (banner_id),
    CONSTRAINT uq_ec_site_banner_order UNIQUE (display_order),
    CONSTRAINT ck_ec_site_banner_order CHECK (display_order BETWEEN 1 AND 4),
    CONSTRAINT ck_ec_site_banner_active CHECK (is_active IN ('Y', 'N'))
);

COMMIT;

-- ============================================================================
-- EC SITE ORDER TABLES
-- Independent from the legacy ORDERS, SALES, and SALES_ITEMS tables.
-- Run this section only when EC_ORDERS and EC_ORDER_ITEMS do not already exist.
-- ============================================================================

CREATE TABLE ec_orders (
    order_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id           NUMBER NOT NULL,
    total_price       NUMBER(12, 2) NOT NULL,
    status            VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    shipping_address  VARCHAR2(500 CHAR) NOT NULL,
    order_date        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_ec_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_ec_orders_user FOREIGN KEY (user_id)
        REFERENCES app_users (user_id),
    CONSTRAINT ck_ec_orders_total CHECK (total_price >= 0),
    CONSTRAINT ck_ec_orders_status CHECK (
        status IN ('PENDING', 'CONFIRMED', 'SHIPPED', 'COMPLETED', 'CANCELLED')
    )
);

CREATE TABLE ec_order_items (
    order_item_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    order_id       NUMBER NOT NULL,
    prod_id        NUMBER NOT NULL,
    quantity       NUMBER(10) NOT NULL,
    unit_price     NUMBER(12, 2) NOT NULL,
    CONSTRAINT pk_ec_order_items PRIMARY KEY (order_item_id),
    CONSTRAINT fk_ec_items_order FOREIGN KEY (order_id)
        REFERENCES ec_orders (order_id),
    CONSTRAINT fk_ec_items_product FOREIGN KEY (prod_id)
        REFERENCES products (prod_id),
    CONSTRAINT uq_ec_items_order_product UNIQUE (order_id, prod_id),
    CONSTRAINT ck_ec_items_quantity CHECK (
        quantity > 0 AND quantity = TRUNC(quantity)
    ),
    CONSTRAINT ck_ec_items_price CHECK (unit_price >= 0)
);

COMMIT;

-- ============================================================================
-- EC site authentication (independent from the existing CUSTOMERS table)
-- Run this section only when APP_USERS does not already exist.
-- ============================================================================

CREATE TABLE app_users (
    user_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name     VARCHAR2(100 CHAR) NOT NULL,
    last_name      VARCHAR2(100 CHAR) NOT NULL,
    email          VARCHAR2(255 CHAR) NOT NULL,
    password_hash  VARCHAR2(100 CHAR) NOT NULL,
    phone          VARCHAR2(30 CHAR),
    address        VARCHAR2(500 CHAR),
    role           VARCHAR2(20 CHAR) DEFAULT 'CUSTOMER' NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_app_users PRIMARY KEY (user_id),
    CONSTRAINT uq_app_users_email UNIQUE (email),
    CONSTRAINT ck_app_users_role CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

-- Oracle unique constraints are normally case-sensitive. This additional
-- function-based unique index prevents both User@example.com and
-- user@example.com from being registered as separate accounts.
CREATE UNIQUE INDEX uq_app_users_email_ci
    ON app_users (LOWER(email));

COMMIT;

-- ============================================================================
-- EC SITE PRODUCT ID SEQUENCE
-- Live PRODUCTS.PROD_ID maximum was verified as 3515 before this DDL was added.
-- Run only when EC_PRODUCT_SEQ does not already exist; never drop/recreate it.
-- ============================================================================

CREATE SEQUENCE ec_product_seq
    START WITH 3516
    INCREMENT BY 1
    NOCYCLE
    CACHE 20;

-- ============================================================================
-- EC SITE PRODUCT IMAGES
-- Isolated image URL/path data; the legacy PRODUCTS table is not altered.
-- Run only when EC_PRODUCT_IMAGES does not already exist.
-- ============================================================================

CREATE TABLE ec_product_images (
    image_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    prod_id     NUMBER(6) NOT NULL,
    image_url   VARCHAR2(500 CHAR) NOT NULL,
    is_primary  CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_ec_product_images PRIMARY KEY (image_id),
    CONSTRAINT fk_ec_product_images_product FOREIGN KEY (prod_id)
        REFERENCES products (prod_id),
    CONSTRAINT ck_ec_product_images_primary CHECK (is_primary IN ('Y', 'N'))
);

-- Oracle stores NULL entries outside a normal unique index. This expression
-- therefore permits many non-primary rows but only one primary row per product.
CREATE UNIQUE INDEX uq_ec_product_primary_image
    ON ec_product_images (CASE WHEN is_primary = 'Y' THEN prod_id END);

COMMIT;

-- ============================================================================
-- EC SITE PRODUCT IMAGE GALLERY (upgrade for an existing EC_PRODUCT_IMAGES)
-- Run these statements once after confirming DISPLAY_ORDER does not exist.
-- Existing image rows and URLs are preserved.
-- ============================================================================

ALTER TABLE ec_product_images ADD display_order NUMBER(1);

MERGE INTO ec_product_images target
USING (
    SELECT image_id,
           ROW_NUMBER() OVER (
               PARTITION BY prod_id
               ORDER BY CASE WHEN is_primary = 'Y' THEN 0 ELSE 1 END,
                        created_at, image_id
           ) AS rn
    FROM ec_product_images
) source
ON (target.image_id = source.image_id)
WHEN MATCHED THEN UPDATE SET target.display_order = source.rn;

ALTER TABLE ec_product_images
    MODIFY display_order DEFAULT 1 NOT NULL;

ALTER TABLE ec_product_images ADD CONSTRAINT ck_ec_product_image_order
    CHECK (display_order BETWEEN 1 AND 4);

ALTER TABLE ec_product_images ADD CONSTRAINT uq_ec_product_image_order
    UNIQUE (prod_id, display_order);

COMMIT;

-- ============================================================================
-- EC SITE PRODUCT CATEGORIES
-- Friendly names for legacy PRODUCTS.CATEGORY_ID values. PRODUCTS is unchanged.
-- Run only when EC_CATEGORIES does not already exist.
-- ============================================================================

CREATE TABLE ec_categories (
    category_id    NUMBER(2) NOT NULL,
    category_name  VARCHAR2(100 CHAR) NOT NULL,
    display_order  NUMBER(3),
    is_active      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CONSTRAINT pk_ec_categories PRIMARY KEY (category_id),
    CONSTRAINT ck_ec_categories_active CHECK (is_active IN ('Y', 'N'))
);

INSERT INTO ec_categories VALUES (11, 'Monitors', 1, 'Y');
INSERT INTO ec_categories VALUES (12, 'Printers', 2, 'Y');
INSERT INTO ec_categories VALUES (13, 'Hard Drives', 3, 'Y');
INSERT INTO ec_categories VALUES (14, 'Memory', 4, 'Y');
INSERT INTO ec_categories VALUES (15, 'Computer Components', 5, 'Y');
INSERT INTO ec_categories VALUES (16, 'Computer Accessories', 6, 'Y');
INSERT INTO ec_categories VALUES (17, 'Storage & Drives', 7, 'Y');
INSERT INTO ec_categories VALUES (19, 'Parts & Power Supplies', 8, 'Y');
INSERT INTO ec_categories VALUES (21, 'Spreadsheet Software', 9, 'Y');
INSERT INTO ec_categories VALUES (22, 'Word Processing Software', 10, 'Y');
INSERT INTO ec_categories VALUES (24, 'Operating Systems', 11, 'Y');
INSERT INTO ec_categories VALUES (25, 'Development Software', 12, 'Y');
INSERT INTO ec_categories VALUES (29, 'Business & Network Software', 13, 'Y');
INSERT INTO ec_categories VALUES (31, 'Office & Communication', 14, 'Y');
INSERT INTO ec_categories VALUES (32, 'Office Supplies', 15, 'Y');
INSERT INTO ec_categories VALUES (33, 'Manuals & Documentation', 16, 'Y');
INSERT INTO ec_categories VALUES (39, 'Industrial Supplies', 17, 'Y');

COMMIT;
-- ============================================================
-- EC SITE CUSTOMER NOTIFICATIONS AND ORDER TRACKING
-- Run only after APP_USERS and EC_ORDERS exist.
-- Existing order/user/product rows are not changed by these tables.
-- ============================================================

CREATE TABLE ec_order_tracking (
    order_id             NUMBER NOT NULL,
    carrier              VARCHAR2(100 CHAR),
    tracking_number      VARCHAR2(100 CHAR),
    shipment_status      VARCHAR2(50 CHAR),
    tracking_information VARCHAR2(1000 CHAR),
    updated_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_ec_order_tracking PRIMARY KEY (order_id),
    CONSTRAINT fk_ec_tracking_order FOREIGN KEY (order_id)
        REFERENCES ec_orders (order_id)
);

CREATE TABLE ec_notifications (
    notification_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id           NUMBER NOT NULL,
    order_id          NUMBER,
    notification_type VARCHAR2(50 CHAR) NOT NULL,
    title             VARCHAR2(200 CHAR) NOT NULL,
    message           VARCHAR2(1000 CHAR) NOT NULL,
    target_url        VARCHAR2(500 CHAR),
    is_read           NUMBER(1) DEFAULT 0 NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    read_at           TIMESTAMP,
    CONSTRAINT pk_ec_notifications PRIMARY KEY (notification_id),
    CONSTRAINT fk_ec_notifications_user FOREIGN KEY (user_id)
        REFERENCES app_users (user_id),
    CONSTRAINT fk_ec_notifications_order FOREIGN KEY (order_id)
        REFERENCES ec_orders (order_id),
    CONSTRAINT ck_ec_notifications_read CHECK (is_read IN (0, 1))
);

CREATE INDEX ix_ec_notifications_user_date
    ON ec_notifications (user_id, created_at DESC);

-- The original check did not support the requested processing/delivery states.
ALTER TABLE ec_orders DROP CONSTRAINT ck_ec_orders_status;
ALTER TABLE ec_orders ADD CONSTRAINT ck_ec_orders_status CHECK (
    status IN ('PENDING','CONFIRMED','PROCESSING','SHIPPED',
               'DELIVERED','COMPLETED','CANCELLED')
);
