<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><c:out value="${product.productName}"/> | NEXORA</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css?v=24"></head><body class="product-details-page"><jsp:include page="/WEB-INF/views/includes/navigation.jsp"/>
<main class="page-container"><a class="back-link" href="${pageContext.request.contextPath}/products">&larr; Back to Products</a><article class="product-detail-layout">
<section class="product-gallery" aria-label="Product images"><div class="product-gallery-main" id="galleryMain"><c:choose><c:when test="${not empty productImages}"><c:set var="firstImage" value="${productImages[0]}"/><img id="galleryMainImage" class="product-gallery-main-image" src="<c:if test='${firstImage.localImage}'>${pageContext.request.contextPath}</c:if><c:out value='${firstImage.imageUrl}'/>" alt="<c:out value='${product.productName}'/>" onerror="this.hidden=true;document.getElementById('galleryPlaceholder').hidden=false"><div id="galleryPlaceholder" class="product-gallery-placeholder" hidden>No image available</div><c:if test="${productImages.size() > 1}"><button class="gallery-arrow gallery-previous" type="button" data-gallery-change="-1" aria-label="Previous image">&#10094;</button><button class="gallery-arrow gallery-next" type="button" data-gallery-change="1" aria-label="Next image">&#10095;</button></c:if></c:when><c:otherwise><div id="galleryPlaceholder" class="product-gallery-placeholder">No image available</div></c:otherwise></c:choose></div>
<c:if test="${not empty productImages}"><div class="product-gallery-thumbnails" role="list" aria-label="Choose product image"><c:forEach var="image" items="${productImages}" varStatus="status"><button class="gallery-thumbnail-button ${status.first?'selected':''}" type="button" data-gallery-index="${status.index}" data-image-url="<c:if test='${image.localImage}'>${pageContext.request.contextPath}</c:if><c:out value='${image.imageUrl}'/>" aria-label="Show image ${status.index + 1}" aria-pressed="${status.first}"><img src="<c:if test='${image.localImage}'>${pageContext.request.contextPath}</c:if><c:out value='${image.imageUrl}'/>" alt="Thumbnail ${status.index + 1} for <c:out value='${product.productName}'/>" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="gallery-thumbnail-placeholder" hidden>No image</span></button></c:forEach></div></c:if></section>
<section class="product-detail-panel"><header class="product-detail-heading"><h1><c:out value="${product.productName}"/></h1><p class="product-detail-price"><c:choose><c:when test="${not empty product.listPrice}">&yen;<fmt:formatNumber value="${product.listPrice}" pattern="#,##0.00"/></c:when><c:otherwise>Not available</c:otherwise></c:choose></p><c:if test="${not empty product.productStatus}"><span class="status"><c:out value="${product.productStatus}"/></span></c:if></header>
<section class="product-specifications"><h2>Product Information</h2><div class="product-spec-row"><span class="product-spec-label">Product ID</span><span class="product-spec-value">${product.productId}</span></div><div class="product-spec-row"><span class="product-spec-label">Category</span><span class="product-spec-value">${empty product.categoryId?'Not available':product.displayCategoryName}</span></div><div class="product-spec-row"><span class="product-spec-label">Supplier</span><span class="product-spec-value">${empty product.supplierId?'Not available':product.supplierId}</span></div><div class="product-spec-row"><span class="product-spec-label">Weight Class</span><span class="product-spec-value">${empty product.weightClass?'Not available':product.weightClass}</span></div><div class="product-spec-row"><span class="product-spec-label">Warranty</span><span class="product-spec-value"><c:choose><c:when test="${not empty product.warrantyPeriod}"><c:out value="${product.warrantyPeriod}"/></c:when><c:otherwise>Not available</c:otherwise></c:choose></span></div><div class="product-spec-row"><span class="product-spec-label">Minimum Price</span><span class="product-spec-value"><c:choose><c:when test="${not empty product.minimumPrice}">&yen;<fmt:formatNumber value="${product.minimumPrice}" pattern="#,##0.00"/></c:when><c:otherwise>Not available</c:otherwise></c:choose></span></div><div class="product-spec-row"><span class="product-spec-label">Catalog</span><span class="product-spec-value"><c:choose><c:when test="${product.catalogUrlDisplayable}"><a href="<c:out value='${product.catalogUrl}'/>" target="_blank" rel="noopener noreferrer">View Catalog</a></c:when><c:otherwise>Not available</c:otherwise></c:choose></span></div></section>
<form class="product-purchase-panel" method="post" action="${pageContext.request.contextPath}/cart/add"><input type="hidden" name="productId" value="${product.productId}"><label for="quantity">Quantity</label><div class="quantity-selector"><button type="button" class="quantity-step" data-change="-1" aria-label="Decrease quantity">&minus;</button><input id="quantity" name="quantity" type="number" value="1" min="1" required><button type="button" class="quantity-step" data-change="1" aria-label="Increase quantity">+</button></div><button class="form-button add-cart-primary" type="submit">Add to Cart</button></form></section>
</article>
<c:if test="${not empty relatedProducts or not empty otherProducts}"><div class="product-recommendations" aria-label="Product recommendations">
<c:if test="${not empty relatedProducts}"><section class="recommendation-section"><h2>You May Also Like</h2><div class="recommendation-grid"><c:forEach var="recommendedProduct" items="${relatedProducts}"><article class="recommendation-card">
<div class="recommendation-image"><c:choose><c:when test="${not empty recommendedProduct.imageUrl}"><img src="<c:if test='${recommendedProduct.localImage}'>${pageContext.request.contextPath}</c:if><c:out value='${recommendedProduct.imageUrl}'/>" alt="<c:out value='${recommendedProduct.productName}'/>" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="recommendation-placeholder" hidden>No image available</div></c:when><c:otherwise><div class="recommendation-placeholder">No image available</div></c:otherwise></c:choose></div>
<div class="recommendation-body"><p class="recommendation-category"><c:out value="${recommendedProduct.displayCategoryName}"/></p><h3><c:out value="${recommendedProduct.productName}"/></h3><p class="recommendation-price"><c:choose><c:when test="${not empty recommendedProduct.listPrice}">&yen;<fmt:formatNumber value="${recommendedProduct.listPrice}" pattern="#,##0.00"/></c:when><c:otherwise>Price not available</c:otherwise></c:choose></p><p class="recommendation-status"><c:choose><c:when test="${not empty recommendedProduct.productStatus}"><c:out value="${recommendedProduct.productStatus}"/></c:when><c:otherwise>Status not available</c:otherwise></c:choose></p><a class="recommendation-link" href="${pageContext.request.contextPath}/product?id=${recommendedProduct.productId}">View Details</a></div>
</article></c:forEach></div></section></c:if>
<c:if test="${not empty otherProducts}"><section class="recommendation-section"><h2>Explore More Products</h2><div class="recommendation-row"><div class="recommendation-grid"><c:forEach var="recommendedProduct" items="${otherProducts}"><article class="recommendation-card">
<div class="recommendation-image"><c:choose><c:when test="${not empty recommendedProduct.imageUrl}"><img src="<c:if test='${recommendedProduct.localImage}'>${pageContext.request.contextPath}</c:if><c:out value='${recommendedProduct.imageUrl}'/>" alt="<c:out value='${recommendedProduct.productName}'/>" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="recommendation-placeholder" hidden>No image available</div></c:when><c:otherwise><div class="recommendation-placeholder">No image available</div></c:otherwise></c:choose></div>
<div class="recommendation-body"><p class="recommendation-category"><c:out value="${recommendedProduct.displayCategoryName}"/></p><h3><c:out value="${recommendedProduct.productName}"/></h3><p class="recommendation-price"><c:choose><c:when test="${not empty recommendedProduct.listPrice}">&yen;<fmt:formatNumber value="${recommendedProduct.listPrice}" pattern="#,##0.00"/></c:when><c:otherwise>Price not available</c:otherwise></c:choose></p><p class="recommendation-status"><c:choose><c:when test="${not empty recommendedProduct.productStatus}"><c:out value="${recommendedProduct.productStatus}"/></c:when><c:otherwise>Status not available</c:otherwise></c:choose></p><a class="recommendation-link" href="${pageContext.request.contextPath}/product?id=${recommendedProduct.productId}">View Details</a></div>
</article></c:forEach></div><aside class="recommendation-more-area" aria-label="View the full product catalog"><a class="recommendation-more-button" href="${pageContext.request.contextPath}/products" aria-label="View all products"><span aria-hidden="true">&#8250;</span></a></aside></div></section></c:if>
</div></c:if></main>
<script>(function(){const buttons=[...document.querySelectorAll('.gallery-thumbnail-button')],main=document.getElementById('galleryMainImage'),placeholder=document.getElementById('galleryPlaceholder');let current=0,startX=null;function show(index){if(!main||!buttons.length)return;current=(index+buttons.length)%buttons.length;main.hidden=false;placeholder.hidden=true;main.src=buttons[current].dataset.imageUrl;buttons.forEach((b,i)=>{b.classList.toggle('selected',i===current);b.setAttribute('aria-pressed',i===current)});}buttons.forEach((b,i)=>b.addEventListener('click',()=>show(i)));document.querySelectorAll('[data-gallery-change]').forEach(b=>b.addEventListener('click',()=>show(current+Number(b.dataset.galleryChange))));const area=document.getElementById('galleryMain');if(area&&buttons.length>1){area.addEventListener('touchstart',e=>startX=e.changedTouches[0].clientX,{passive:true});area.addEventListener('touchend',e=>{if(startX===null)return;const delta=e.changedTouches[0].clientX-startX;if(Math.abs(delta)>45)show(current+(delta<0?1:-1));startX=null},{passive:true});}document.querySelectorAll('.quantity-step').forEach(b=>b.addEventListener('click',()=>{const i=document.getElementById('quantity');i.value=Math.max(1,(parseInt(i.value,10)||1)+Number(b.dataset.change));}));})();</script></body></html>







