<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Banner Management | NEXORA</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css?v=23"></head><body><jsp:include page="/WEB-INF/views/includes/navigation.jsp"/><main class="page-container"><div class="page-heading"><div><h1>Banner Management</h1><p>${bannerCount} / 4 banners</p></div><a href="${pageContext.request.contextPath}/admin">Admin Dashboard</a></div>
<c:if test="${param.message=='created'}"><div class="message success">Banner uploaded successfully.</div></c:if><c:if test="${param.message=='updated'}"><div class="message success">Banner updated.</div></c:if><c:if test="${param.message=='removed'}"><div class="message success">Banner removed.</div></c:if><c:if test="${param.message=='limit'}"><div class="message error">Maximum 4 banners.</div></c:if><c:if test="${param.message=='orderUsed'}"><div class="message error">That display order is already used.</div></c:if><c:if test="${param.message=='link'}"><div class="message error">Use /products, /product, or a complete HTTPS link.</div></c:if><c:if test="${param.message=='order'}"><div class="message error">Display order must be between 1 and 4.</div></c:if><c:if test="${param.message=='title'}"><div class="message error">Title must not exceed 120 characters.</div></c:if><c:if test="${param.message=='empty'}"><div class="message error">Please select a banner image.</div></c:if><c:if test="${param.message=='type'}"><div class="message error">Only JPG and PNG images are supported.</div></c:if><c:if test="${param.message=='large'}"><div class="message error">Banner image must be 5 MB or smaller.</div></c:if><c:if test="${param.message=='invalid'}"><div class="message error">The uploaded file is not a valid image.</div></c:if><c:if test="${param.message=='failed'}"><div class="message error">Banner upload failed. Please try again.</div></c:if>
<div class="admin-banner-list"><c:forEach var="banner" items="${banners}"><article class="admin-banner-card"><div class="admin-banner-preview"><img src="${pageContext.request.contextPath}<c:out value='${banner.imageUrl}'/>" alt="<c:out value='${banner.title}'/>" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="banner-image-placeholder" hidden>Banner unavailable</div></div><form method="post" action="${pageContext.request.contextPath}/admin/banners"><input type="hidden" name="bannerId" value="${banner.bannerId}"><label>Title</label><input name="title" maxlength="120" value="<c:out value='${banner.title}'/>"><label>Link</label><input name="linkUrl" maxlength="500" value="<c:out value='${banner.linkUrl}'/>" placeholder="/product?id=1733"><div class="form-grid"><div><label>Display order</label><input name="displayOrder" type="number" min="1" max="4" required value="${banner.displayOrder}"></div><div><label>Active</label><select name="isActive"><option value="Y" ${banner.active?'selected':''}>Yes</option><option value="N" ${not banner.active?'selected':''}>No</option></select></div></div><button class="small-button" type="submit" name="action" value="update">Save Changes</button><button class="danger-button" type="submit" name="action" value="remove">Remove</button></form></article></c:forEach></div>
<c:choose><c:when test="${bannerCount >= 4}"><div class="message error">Maximum 4 banners.</div></c:when><c:otherwise><section class="form-card form-card-wide banner-upload-card"><h2>Upload New Banner</h2><form method="post" enctype="multipart/form-data" action="${pageContext.request.contextPath}/admin/banners/upload"><label for="imageFile">JPG or PNG (maximum 5 MB)</label><input id="imageFile" name="imageFile" type="file" accept="image/jpeg,image/png,.jpg,.jpeg,.png" required><label for="title">Optional title</label><input id="title" name="title" maxlength="120"><label for="linkUrl">Optional link</label><input id="linkUrl" name="linkUrl" maxlength="500" placeholder="/products?status=orderable"><div class="form-grid"><div><label for="displayOrder">Display order</label><input id="displayOrder" name="displayOrder" type="number" min="1" max="4" required></div><div><label for="isActive">Active</label><select id="isActive" name="isActive"><option value="Y">Yes</option><option value="N">No</option></select></div></div><button class="form-button" type="submit">Upload New Banner</button></form></section></c:otherwise></c:choose></main></body></html>




