<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Order #${order.orderId} | NEXORA</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css?v=23"></head><body><jsp:include page="/WEB-INF/views/includes/navigation.jsp"/><main class="page-container"><a class="back-link" href="${pageContext.request.contextPath}/admin/orders">&larr; Back to Orders</a><c:if test="${param.message=='tracking'}"><div class="message success">Tracking information updated and the customer was notified.</div></c:if><c:if test="${param.message=='tracking-unchanged'}"><div class="message">Nothing changed. No duplicate notification was created.</div></c:if><section class="order-detail-header"><h1>Order #${order.orderId}</h1><p><strong>Customer:</strong> <c:out value="${order.customerName}"/> (<c:out value="${order.customerEmail}"/>)</p><p><strong>Status:</strong> <c:out value="${order.status}"/></p><p><strong>Shipping:</strong> <c:out value="${order.shippingAddress}"/></p><p><strong>Total:</strong> &yen;<fmt:formatNumber value="${order.totalPrice}" pattern="#,##0.00"/></p></section>
<section class="tracking-card admin-tracking-card"><h2>Shipping &amp; Tracking</h2><form method="post" action="${pageContext.request.contextPath}/admin/orders/tracking"><input type="hidden" name="orderId" value="${order.orderId}"><div class="form-grid"><div><label for="carrier">Carrier</label><input id="carrier" name="carrier" maxlength="100" value="<c:out value='${tracking.carrier}'/>"></div><div><label for="trackingNumber">Tracking Number</label><input id="trackingNumber" name="trackingNumber" maxlength="100" value="<c:out value='${tracking.trackingNumber}'/>"></div><div><label for="shipmentStatus">Shipment Status</label><input id="shipmentStatus" name="shipmentStatus" maxlength="50" value="<c:out value='${tracking.shipmentStatus}'/>"></div><div><label for="trackingInformation">Tracking Information</label><input id="trackingInformation" name="trackingInformation" maxlength="1000" value="<c:out value='${tracking.trackingInformation}'/>"></div></div><button class="form-button" type="submit">Save Tracking Update</button></form></section>
<div class="cart-table-wrap"><table class="cart-table order-items-table"><thead><tr><th>Product</th><th>Price captured</th><th>Quantity</th><th>Subtotal</th></tr></thead><tbody><c:forEach var="i" items="${orderItems}"><tr><td><div class="order-product"><c:choose><c:when test="${not empty i.imageUrl}"><div class="ec-product-thumbnail-wrapper"><img class="ec-product-thumbnail" src="<c:if test='${i.localImage}'>${pageContext.request.contextPath}</c:if><c:out value='${i.imageUrl}'/>" alt="<c:out value='${i.productName}'/>" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="ec-product-thumbnail-placeholder" hidden>No image</div></div></c:when><c:otherwise><div class="ec-product-thumbnail-wrapper"><div class="ec-product-thumbnail-placeholder" aria-label="No image available for ${i.productName}">No image</div></div></c:otherwise></c:choose><div><strong><c:out value="${i.productName}"/></strong><span>Product ID: ${i.prodId}</span></div></div></td><td>&yen;<fmt:formatNumber value="${i.unitPrice}" pattern="#,##0.00"/></td><td>${i.quantity}</td><td>&yen;<fmt:formatNumber value="${i.subtotal}" pattern="#,##0.00"/></td></tr></c:forEach></tbody></table></div></main></body></html>







