<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Orders | NEXORA</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css?v=23"></head><body><jsp:include page="/WEB-INF/views/includes/navigation.jsp"/><main class="page-container"><h1>Order Management</h1><c:if test="${message=='status'}"><div class="message success">Order status updated and the customer was notified.</div></c:if><c:if test="${message=='unchanged'}"><div class="message">The order already had that status. No duplicate notification was created.</div></c:if><div class="cart-table-wrap"><table class="cart-table"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Status</th><th>Total</th><th>Address</th><th>Actions</th></tr></thead><tbody><c:forEach var="o" items="${orders}"><tr><td>#${o.orderId}</td><td><c:out value="${o.customerName}"/><span><c:out value="${o.customerEmail}"/></span></td><td><fmt:formatDate value="${o.orderDate}" pattern="yyyy-MM-dd HH:mm"/></td><td><c:out value="${o.status}"/></td><td>&yen;<fmt:formatNumber value="${o.totalPrice}" pattern="#,##0.00"/></td><td><c:out value="${o.shippingAddress}"/></td><td><a href="${pageContext.request.contextPath}/admin/orders/detail?id=${o.orderId}">Details</a><form class="inline-form status-form" method="post" action="${pageContext.request.contextPath}/admin/orders/status"><input type="hidden" name="orderId" value="${o.orderId}"><select name="status"><c:forEach var="s" items="${['PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','COMPLETED','CANCELLED']}"><option value="${s}" ${o.status==s?'selected':''}>${s}</option></c:forEach></select><button class="small-button">Update</button></form></td></tr></c:forEach></tbody></table></div></main></body></html>







