<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Products | NEXORA</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css?v=23"></head>
<body><jsp:include page="/WEB-INF/views/includes/navigation.jsp"/><main class="page-container">
<div class="page-heading"><div><h1>Product Management</h1><p>Product IDs are generated by Oracle sequence EC_PRODUCT_SEQ.</p></div><a class="primary-button" href="${pageContext.request.contextPath}/admin/products/new">Add New Product</a></div>
<c:if test="${message=='referenced'}"><div class="message error">This product has order history and cannot be deleted. Set its status to obsolete instead.</div></c:if>
<c:if test="${message=='updated'}"><div class="message success">Product updated.</div></c:if>
<div class="cart-table-wrap"><table class="cart-table"><thead><tr><th>ID</th><th>Name</th><th>Status</th><th>List price</th><th>Minimum</th><th>Category</th><th>Actions</th></tr></thead><tbody>
<c:forEach var="p" items="${products}"><tr><td>${p.productId}</td><td><c:out value="${p.productName}"/></td><td><c:out value="${p.productStatus}"/></td><td>${p.listPrice}</td><td>${p.minimumPrice}</td><td>${p.categoryId}</td><td><a href="${pageContext.request.contextPath}/admin/products/edit?id=${p.productId}">Edit</a><form class="inline-form" method="post" action="${pageContext.request.contextPath}/admin/products/delete"><input type="hidden" name="productId" value="${p.productId}"><button class="danger-button" type="submit">Delete</button></form></td></tr></c:forEach>
</tbody></table></div><nav class="pagination"><c:forEach begin="1" end="${totalPages}" var="n"><a href="?page=${n}">${n}</a></c:forEach></nav></main></body></html>








